name: pokedex_case_study
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #? Core (Stage Management - Network - Storage - Cache - DI)
  dio: ^5.3.2 #Dio is a powerful and easy-to-use HTTP client for making network requests in Flutter.
  hooks_riverpod: ^2.4.0 #Allows you to define providers and manage your app's state, making it easier to handle data and dependencies.
  riverpod_annotation: ^2.1.5 #Part of the Riverpod state management library, which helps manage application state in a clean and efficient way.
  hive_flutter: ^1.1.0 #Lightweight and fast NoSQL database for Flutter, and hive_flutter provides Flutter-specific bindings for it.

  #? UI - View
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0 #It's useful for displaying images in your app without making unnecessary network requests for the same image multiple times.
  google_fonts: ^6.1.0 #Google Fonts provides access to a wide range of open-source fonts hosted by Google.
  flutter_hooks: ^0.20.1 # Flutter Hooks is a library for using hooks in Flutter, which are a way to manage stateful logic in a more functional and reusable manner.
  palette_generator: ^0.3.3+3 #Palette Generator is used to extract prominent colors from images.
  percent_indicator: ^4.2.3 #Palette Generator is used to extract prominent colors from images.

  #?Routing
  auto_route: ^7.8.3 #Auto Route simplifies the process of defining and managing navigation routes in Flutter apps.

  #? Utilities
  logger: ^2.0.2 #Logger provides a simple and customisable logging system to track information, warnings and errors during development.
  json_annotation: ^4.8.1 #It is part of the JSON serialization process in Flutter. It generates JSON serialization code based on your Dart classes.
  freezed_annotation: ^2.4.1 #It is used for creating immutable data classes with ease. It generates code for creating data classes with a copy constructor and equality checks.
  equatable: ^2.0.5 #It is a library for easily implementing value-based equality for your Dart objects. It helps improve performance when comparing objects.
  pretty_dio_logger: ^1.3.1 # This package extends the Dio HTTP client with a customizable and human-readable logging system for HTTP requests and responses.

dev_dependencies:
  build_runner: ^2.4.6 #build_runner is a tool for code generation in Dart and Flutter projects.It's used for automatically generate code, reducing boilerplate and manual work.
  json_serializable: ^6.7.1 #This package works alongside build_runner to automatically generate JSON serialization and deserialization code for your Dart classes.
  freezed: ^2.4.2 # freezed is a code generation package that simplifies the creation of immutable data classes and unions (sum types) in Dart.
  hive_generator: ^2.0.1 #hive_generator is used with the Hive database package to generate code for storing and retrieving objects in a Hive box.
  riverpod_generator: ^2.3.2 #riverpod_generator works with the Riverpod state management library to generate code for providers and other state management-related tasks.
  auto_route_generator: ^7.3.1 #auto_route_generator complements the auto_route package and generates code for route handling and navigation in your Flutter app.
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
